version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: export PYTHONPATH=`pwd`/..; echo $PYTHONPATH # todo: install package
          name: Install package
      - run:
          command: echo $PYTHONPATH; python examples/ls_api_surveytest.py 
          name: Test_LS_integration

workflows:
  main:
    jobs:
      - build-and-test

